### ISSUE TITLE
Version become empty string when nginx-build is installed by go get

### ISSUE THREAD

**Issue by cubicdaiya** [cubicdaiya/nginx-build#26]
```
$ go get -u github.com/cubicdaiya/nginx-build
$ rehash
$ nginx-build -version
nginx-build 
Compiler: gc go1.9.2
Copyright (C) 2014-2017 Tatsuhiko Kubo <cubicdaiya _at_ gmail.com>
```

**Comment by gszr** [comment]
This is expected, given the version is specified by the `NginxBuildVersion` variable, which is filled at build-time with `-ldflags`. We could:
- Specify `-ldflags` in `go get` (if it supports that) - not quite nice IMO
- Define a default value for `NginxBuildVersion`, so `go get` would build the binary with that. It'd be very nice if we could in this case have the version be the sha of the commit we're building (not quite sure how we could achieve that with minimum manual intervention or a git hook), but simply having the default be `master` (or similar) would already be something :)

**Comment by cubicdaiya** [comment]
Yes. OTOH, I think it looks a little strange behavior from the user.

**Comment by catatsuy** [comment]
@cubicdaiya  You can use `debug.ReadBuildInfo`.
refs: https://github.com/catatsuy/notify_slack/pull/71/files

**Comment by cubicdaiya** [comment]
Today we can use `go install`. So, I close this issue.

```
$ go install github.com/cubicdaiya/nginx-build@latest
go: downloading github.com/cubicdaiya/nginx-build v0.13.0
```
