### ISSUE TITLE
Changing url of module does not redownload repo

### ISSUE THREAD

**Issue by a666** [cubicdaiya/nginx-build#37]
Hello,
I made the following change into my modules.ini file:
```diff
[ngx_brotli]
form=git
- url=https://github.com/google/ngx_brotli.git
+ url=https://github.com/eustas/ngx_brotli.git
shprov=git submodule update --init
```
Unfortunately that change seems to do nothing. 
Perhaps a check for changes like this could be implemented?

**Run information**
Ubuntu 18.04
go version go1.10.2 linux/amd64
nginx-build, latest, built via go get

**Command**
`nginx-build -m nginx_modules.ini`

**Comment by cubicdaiya** [comment]
> nginx-build -m nginx_modules.ini

nginx-build requires to set working directory with -d.
