### ISSUE TITLE
choose between stable and mainline

### ISSUE THREAD

**Issue by mathieu-aubin** [cubicdaiya/nginx-build#38]
As os now, you seem to be using mainline per default... i am very aware that you can change the version number to a stable version (well, in fact i havnt tried, i'm just assuming) but it'd still be a nice feature to add toggles like -mainline or -stable or something of sorts. Just something 'convenient'

**Comment by cubicdaiya** [comment]
nginx's new mainline and stable versions have been released per year in these past years. Under such situation, the number that `-mainline` and `-stable` indicates chages per year. So I'll not implement such feature. Instead, nginx-build provides the feature to specify the nginx version built.

```
nginx-build -d work -v 1.14.0
```

Thanks.

**Comment by mathieu-aubin** [comment]
As i wrote, yes i understand that its possible to change version number.

Mainline and stable are 2 different things and once mainline moves to stable, its added to stable branch.

You can view the difference from every packages manager's urls, be it debian [mainline](https://nginx.org/packages/mainline/debian) / [stable](https://nginx.org/packages/debian) or redhat related [mainline](https://nginx.org/packages/mainline/centos) / [stable](https://nginx.org/packages/centos). [nginx.org's download](https://nginx.org/en/download.html) page does also clearly show a difference between mainline and stable. 

Now from here, you do what you want. If you do not want/accept outside constructive criticism, so be it. The point of this was only to help you provide a better, more complete utility.
