### ISSUE TITLE
flag provided but not defined: -p1

### ISSUE THREAD

**Issue by Brainiarc7** [cubicdaiya/nginx-build#55]
Hello there,

Trying to configure nginx with a patch applied prior to the build as shown:

```sh
~/go/bin/nginx-build -d $PWD -v 1.16.1 -patch < ../nginx/quiche/extras/nginx/nginx-1.16.patch -patch-opt "-p1" -c configure.production
```

Results in the error message above.

**Comment by cubicdaiya** [comment]
Remove `<` after `-patch`.

**Comment by Brainiarc7** [comment]
Okay, will do and retest. Thanks.
