### ISSUE TITLE
ftp.pcre.org is not available

### ISSUE THREAD

**Issue by toritori0318** [cubicdaiya/nginx-build#72]
Hello,
Currently, https://ftp.pcre.org does not seem to be available.  

According to the [official website](https://www.pcre.org/), it says the following.  

```
Note that the former ftp.pcre.org FTP site is no longer available. You will need to update any scripts that download PCRE source code to download via HTTPS, Git, or Subversion from the new home on GitHub instead.
```

You may need to change to a different URL.

**Comment by cubicdaiya** [comment]
Thank you for your report. I have viewed the official website and considered the plan. My current plan is following.

- Make `-pcre` option unavailable for the moment
  - Compiling nginx with pcre2 fails for now
- Revive `-pcre` option after nginx starts to support pcre2
