### ISSUE TITLE
I want pre-built binaries distributed on Release.

### ISSUE THREAD

**Issue by catatsuy** [cubicdaiya/nginx-build#78]
refs:
https://github.com/catatsuy/notify_slack/blob/master/.github/workflows/release.yml
https://github.com/catatsuy/notify_slack/blob/master/.goreleaser.yml

**Comment by catatsuy** [comment]
@cubicdaiya How did you create the release? If you push the tag, it should work with your current setup.

**Comment by cubicdaiya** [comment]
Now I'm working on some compatibility breaking changes. Please wait for a while.

**Comment by cubicdaiya** [comment]
@catatsuy I released the latest release just now. Thank you for your contribution.

**Comment by catatsuy** [comment]
Thank you! @cubicdaiya
